euler70: euler70.c ../sets/libsets.a
	gcc -s -O3 euler70.c -o euler70.exe -lsets -L../sets -I../sets

euler70_d: euler70.c ../sets/libsets_d.a
	gcc -g euler70.c -o euler70_debug.exe -lsets_d -L../sets -I../sets